export enum ApiRoutes {
  GET_LOCALES = "/api/i18n/locales",
  GET_HEADER_DATA = "/api/header-section",
  GET_HERO_SECTION_DATA = "/api/hero-section",
  GET_ABOUT_SECTION_DATA = "/api/about-section",
  GET_PILLARS_SECTION_DATA = "/api/pillar-section",
  GET_PRODUCTION_SECTION_DATA = "/api/production-section",
  GET_AGE_MODAL_SECTION_DATA = "/api/age-modal",
  GET_FOOTER_SECTION_DATA = "/api/footer-section",
  GET_CONTACTS_SECTION_DATA = "/api/contacts-section",
  GET_CATALOGUE_SECTION_DATA = "/api/catalogue-section",
  GET_PRODUCTS = "/api/products",
  GET_FORMATS = "/api/formats",
  GET_BRANDS = "/api/brands",
  GET_FILTER_TYPES = "/api/filter-types",
  GET_PRODUCT_CARD = "/api/product-card",
  GET_SECTIONS_META = "/api/sections-metas",
  POST_MESSAGE = "/api/messages",
  GET_SUBSCRIBERS = "/api/subscribers",
}
