export * from "./getAboutSection";
export * from "./getAgeModalSection";
export * from "./getCatalogueSection";
export * from "./getContactsSection";
export * from "./getFooterSection";
export * from "./getHeaderSection";
export * from "./getHeroSection";
export * from "./getPilarsSection";
export * from "./getProductionSection";
