import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return <div className={`${robotoSans.variable} antialiased`}>{children}</div>;
}
