import { getHeaderData, getLocales, getSectionsMeta } from "@/app/actions";
import { Locale } from "@/app/types";
import { Header } from "@/app/ui";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { redirect } from "next/navigation";
import { ReactNode } from "react";
import QueryProvider from "../ui/providers/QueryProvider";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: { lang: Locale };
}>) {
  const { lang } = await params;
  const sectionsMeta = await getSectionsMeta(lang);
  const headerData = await getHeaderData(lang);
  const locales = await getLocales();

  if (!locales?.includes(lang)) {
    redirect(`/${locales[0]}`);
  }

  return (
    <div className={`${robotoSans.variable} antialiased`}>
      <main className={"overflow-hidden"}>
        <Header headerData={headerData} sectionsData={sectionsMeta} />
        <QueryProvider>{children}</QueryProvider>
      </main>
    </div>
  );
}
