import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: { lang: string };
}>) {
  const { lang } = await params;
  return (
    <html lang={lang}>
      <body className={`${robotoSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
